name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - pip
  - pip:
      - numpy
      - pandas
      - geopandas
      - sage_data_client
      - matplotlib
      - matplotlib.dates
      - metpy.calc
      - metpy.units
