name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - geopandas
  - numpy
  - pandas
  - matplotlib
  - metpy
  - pip
  - pip:
      - sage_data_client
